# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    # - run: npm test
    - name: build the docker image with latest tag
      run: docker build -t meow-meow-ec2-ci-cd .
    - name: Stop existing container on port 80 (if running)
      run: |
          if [[ $(docker ps -q -f publish=80) ]]; then
          docker stop $(docker ps -q -f publish=80)
          fi
    - name: run the docker container on port 80 and bye bye
      run: docker run -d -p 80:3000 --rm meow-meow-ec2-ci-cd
